#+TITLE: Building, Installing, and Playing

* Building

To build and use LightClick we advise that you use the [[https://github.com/idris-lang/Idris2][latest development version]] of Idris2 due to issues with Idris2 totality checker.

One Idris2 has been installed you can build the project with:

#+begin_src bash
make lightclick
#+end_src

The output should look something like:

#+begin_src bash
1/52: Building Toolkit.Data.DList (src/Toolkit/Data/DList.idr)
2/52: Building Toolkit.Data.DList.DeBruijn (src/Toolkit/Data/DList/DeBruijn.idr)
3/52: Building Toolkit.Decidable.Equality.Indexed (src/Toolkit/Decidable/Equality/Indexed.idr)
4/52: Building Toolkit.Data.DVect (src/Toolkit/Data/DVect.idr)
6/52: Building Toolkit.Data.Vect.Extra (src/Toolkit/Data/Vect/Extra.idr)
7/52: Building LightClick.Types.Meta (src/LightClick/Types/Meta.idr)
15/52: Building LightClick.Types (src/LightClick/Types.idr)
17/52: Building LightClick.Terms (src/LightClick/Terms.idr)
18/52: Building LightClick.Values (src/LightClick/Values.idr)
19/52: Building LightClick.IR.ModuleCentric (src/LightClick/IR/ModuleCentric.idr)
20/52: Building Language.SystemVerilog.MetaTypes (src/Language/SystemVerilog/MetaTypes.idr)
21/52: Building LightClick.IR.Channel.MicroSV.Error (src/LightClick/IR/Channel/MicroSV/Error.idr)
23/52: Building Language.SystemVerilog.Micro (src/Language/SystemVerilog/Micro.idr)
24/52: Building LightClick.IR.Channel.MicroSV.Update (src/LightClick/IR/Channel/MicroSV/Update.idr)
25/52: Building Toolkit.Data.DVect.Elem (src/Toolkit/Data/DVect/Elem.idr)
26/52: Building Toolkit.Data.DList.Elem (src/Toolkit/Data/DList/Elem.idr)
28/52: Building LightClick.Types.Equality (src/LightClick/Types/Equality.idr)
29/52: Building LightClick.Types.Compatibility (src/LightClick/Types/Compatibility.idr)
30/52: Building LightClick.Connection (src/LightClick/Connection.idr)
31/52: Building LightClick.Types.Usage (src/LightClick/Types/Usage.idr)
32/52: Building LightClick.Env (src/LightClick/Env.idr)
33/52: Building LightClick.Check (src/LightClick/Check.idr)
34/52: Building LightClick.IR.ChannelCentric (src/LightClick/IR/ChannelCentric.idr)
35/52: Building LightClick.IR.Channel.Normalise.LetFloat (src/LightClick/IR/Channel/Normalise/LetFloat.idr)
36/52: Building LightClick.IR.Channel.Normalise.Merge (src/LightClick/IR/Channel/Normalise/Merge.idr)
37/52: Building LightClick.IR.Channel.Normalise.FreshBinders (src/LightClick/IR/Channel/Normalise/FreshBinders.idr)
38/52: Building LightClick.IR.Channel.Normalise (src/LightClick/IR/Channel/Normalise.idr)
39/52: Building LightClick.IR.Channel.MicroSV.InterpTy (src/LightClick/IR/Channel/MicroSV/InterpTy.idr)
40/52: Building LightClick.IR.Channel.MicroSV.Intermediate (src/LightClick/IR/Channel/MicroSV/Intermediate.idr)
41/52: Building LightClick.IR.Channel.MicroSV (src/LightClick/IR/Channel/MicroSV.idr)
50/52: Building LightClick.DSL.Convert (src/LightClick/DSL/Convert.idr)
51/52: Building Language.SystemVerilog.Micro.Pretty (src/Language/SystemVerilog/Micro/Pretty.idr)
52/52: Building LightClick.Main (src/LightClick/Main.idr)
#+end_src

and take around 10-15 seconds to check:

#+begin_src bash
10.57user 0.45system 0:11.06elapsed 99%CPU (0avgtext+0avgdata 267244maxresident)k
0inputs+28088outputs (0major+235691minor)pagefaults 0swaps
#+end_src

* Installing

We have yet to add installation scripts or turn this into a serious tool to play with.
This might come later.

That being said, you can copy the binary from =build/exec= to a well known location under =PATH= and you should be able to use it from there.

* Playing

LightClick is a very simple language with a simple UX.
We do not provide anything fancy as our interest at the moment is in the tool itself and not necessarily its use by others.

There are examples in the directory called =tests=.
